### ISSUE TITLE
__get on a responseObject returns an uncaught exception

### ISSUE THREAD

**Issue by bureaublanc** [fw4-bvba/whise-api#4]
__get() on a responseObject returns a uncaught exception when the property does not exists.
validatePropertyName() should return false I guess instead of throwing an exception?

**Comment by Fyrts** [comment]
We've deliberately chosen to throw an exception instead of triggering a notice (which is how PHP usually deals with undefined properties), because we consider it important to explicitly handle missing data. If a response is missing data that you expect to be there, it might be unwise to simply trigger a notice and have the script carry on, risking potential data loss.

Could you perhaps use `isset()` or `empty()` to check if the data is present, or use the null coalescing operator to provide a fallback value (like `echo $estate->rooms ?? 0`)? If not, which data appears to be missing?

**Comment by bureaublanc** [comment]
Thanks for your feedback. The coalescing operator is a good solution.
The client gave me list of fields in Whise that should be checked and I if they are filled in be displayed on the website.
Since it's the first time I'm working on a Whise integration I'm still looking for the best way to do that since some values can be found by the property name and others by an id in the 'details' property in the reponse. Any tips on this?

**Comment by Fyrts** [comment]
Your biggest help would probably be the official documentation, and the [detail](https://api.whise.eu/reference?item=detail&lang=nl-BE) and [subdetail](https://api.whise.eu/reference?item=subdetail&lang=nl-BE) reference pages for where to find each field. We usually convert the details into an associative array with subdetail id as key.
